server:
  port: 8084

spring:
  cloud:
    nacos:
      discovery:
      #nacos注册中心
        server-addr: 192.168.0.102:8848

  application:
    name: server-consumer-feign

  mvc:
    servlet:
      load-on-startup: 1

  client:
    config:
      default:
        #readTimeout: 20000
         retryer: feign.Retryer.Default


# 断路器配置:com.netflix.hystrix.HystrixCommandProperties
feign:
  hystrix:
    enabled: true
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 20000



