server:
  port: 8084

spring:
  application:
    name: server-consumer-feign
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.0.21:8848

#hystrix功能开关
feign:
  hystrix:
    enabled: false
  client:
    config:
      default:
        readTimeout : 5000
        retryer: feign.Retryer.Default

# ribbon 可配置 com.netflix.client.config.DefaultClientConfigImpl
ribbon:
  ReadTimeout: 5000
  ConnectTimeout: 5000
  OkToRetryOnAllOperations: false

# hystrix 可配置 hystrix:com.netflix.hystrix.HystrixCommandProperties
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 5000

