server:
  port: 8081
spring:
  application:
    name: service-provider

  cloud:
    nacos:
      discovery:
        server-addr: 192.168.0.22:8848
        weight: 1
    sentinel:
        transport:
          port: 8719
          dashboard: localhost:8080
        eager: true
        enabled: true
        filter:
          enabled: true